name: Deploy blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/source \
        circleci/clojure:latest /bin/bash -c "cd /source && lein run"
        
    - name: Publish
      uses: crazy-max/ghaction-github-pages@v2.1.1
      with:
        build_dir: ${{ github.workspace }}/public
        fqdn: unfolded.dev
        jekyll: false
