name: Deploy blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: circleci/clojure

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: lein run
        
    - name: Publish
      uses: crazy-max/ghaction-github-pages@v2.1.1
      with:
        build_dir: public
        fqdn: unfolded.dev
        jekyll: false
