name: Deploy blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker build -t cryogen .
        docker run -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app cryogen

    - name: Publish
      uses: crazy-max/ghaction-github-pages@v2.1.1
      with:
        build_dir: public
        fqdn: unfolded.dev
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

